name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: pwsh _build/test.ps1
    - name: Publish coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        path-to-lcov: "./coverage/coverage.info"
