name: Publish package
on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    # extract tag name
    - id: branch_name
      name: Get branch name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:CI_BUILD=true -p:Version=$SOURCE_TAG
      env:
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    - name: Test
      run: pwsh _build/test.ps1 -Configuration Release -Rebuild False -SourceLink false
    - name: Create package
      run: |
        echo $SOURCE_NAME
        echo $SOURCE_BRANCH
        echo $SOURCE_TAG
        dotnet pack src/MobileDetect/MobileDetect.csproj --no-build --configuration Release /p:Packing=true /p:PackageOutputPath=$GITHUB_WORKSPACE/.nupkgs /p:CI_BUILD=true -p:Version=$SOURCE_TAG
      env:
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    - name: PushNuget
      run: dotnet nuget push "$GITHUB_WORKSPACE/.nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.PUBLISH_TO_NUGET_ORG}} --skip-duplicate
    - name: PushGithub
      run: dotnet nuget push "$GITHUB_WORKSPACE/.nupkgs/*.nupkg" --source $SOURCE_URL --api-key $NUGET_AUTH_TOKEN --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
        SOURCE_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
